#!/bin/bash
# Convert text files from $TXTBASE directory to
# man pages in $MANBASE directory.
# (C) Vladimir Stavrinov <vstavrinov@gmail.com>

MANBASE=man
TXTBASE=txt
HTMLBASE=html

type txt2man > /dev/null ||
exit 1

for TXT in $TXTBASE/*.[1-8].txt; do
	MAN=$(basename $TXT .txt)
	SECTION=${MAN##*.}
	TITLE=${MAN%.?}
	#txt2man -s $SECTION -t $TITLE $TXT > $MANBASE/$MAN
	#man -Hcat $MANBASE/$MAN > $HTMLBASE/$MAN.html
	#if [ -n "$1" ]; then
	#	man -Hcat $MANBASE/$MAN > $HTMLBASE/$MAN.html
	#fi
done

